server.port=5000
spring.application.name=marketplace-backend

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://kucheakash_db_user:UiKpPCPFSYvIcnHl@cluster0.xhtuuct.mongodb.net/threadloop?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.auto-index-creation=true

# Multipart Upload Configuration
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB

# Logging
logging.level.com.threadloop.marketplace=INFO
logging.level.org.springframework.data.mongodb=INFO
logging.level.org.springframework.web=INFO

# Cloudinary Configuration
cloudinary.cloud-name=eg1xfwym
cloudinary.api-key=135659887613461
cloudinary.api-secret=d8wPkrEqV06Zs_rgSZqlBFWBDqo
